apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
spec:
  defaultBackend:
    service:
      name: argocd-server
      port:
        name: https
  ingressClassName: tailscale
 