apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault-secret-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - https://github.com/gezb/homelab.git
  - https://helm.releases.hashicorp.com
  destinations:
  - namespace: vault
    server: https://kubernetes.default.svc
    name: in-cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true