apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secret-operator-helm
  namespace: argocd
spec:
  project: vault-secret-operator
  source:
    chart: vault-secrets-operator
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.8.1
    helm:
      releaseName: vault-secrets-operator
      valuesObject:
        defaultVaultConnection:
          enabled: true
          address: https://vault.gezb.co.uk
        defaultAuthMethod:
          enabled: true
          namespace: vault
          method: kubernetes
          mount: kubernetes
          kubernetes:
            role: vault-secrets-operator
            serviceAccount: vault
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault