apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: csi-proxmox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - https://github.com/gezb/homelab.git
  destinations:
  - namespace: csi-proxmox
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: kube-node-lease 
    server: https://kubernetes.default.svc
    name: in-cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true