apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/gezb/homelab.git
    targetRevision: HEAD  # For Helm, this refers to the chart version.
    path: gitops/homelab-cluster/monitoring/kube-prometheus/manifests
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  
  revisionHistoryLimit: 1