apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - https://github.com/gezb/homelab.git
  - https://grafana.github.io/helm-charts
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: kube-system
    server: https://kubernetes.default.svc
    name: in-cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true