apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  source:
    repoURL: https://github.com/gezb/homelab.git
    targetRevision: HEAD 
    path: gitops/homelab-cluster/namespaces
    directory:
      recurse: false
      include: '*.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated: 
      prune: false 
      selfHeal: true 
   
  revisionHistoryLimit: 1