apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tailscale
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
  - https://github.com/gezb/homelab.git
  destinations:
  - namespace: tailscale
    server: https://kubernetes.default.svc
    name: in-cluster
